name: "Aws OIDC Check"

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read
  id-token: write

jobs:
  awslogin:
    outputs:
      aws_access_key_id: ${{ steps.export-creds.outputs.aws_access_key_id }}
      aws_secret_access_key: ${{ steps.export-creds.outputs.aws_secret_access_key }}
      aws_session_token: ${{ steps.export-creds.outputs.aws_session_token }}
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::206080133608:role/BedRockRedFlag
          aws-region: us-east-1
          output-credentials: true
      - name: Check variables
        run: |
          echo ${{steps.creds.outputs.aws_access_key_id}}
          echo ${{steps.creds.outputs.aws_secret_access_key}}
          echo ${{steps.creds.outputs.aws_session_token}}
          echo $AWS_REGION
          echo $AWS_ACCESS_KEY_ID
          echo ${{env.AWS_ACCESS_KEY_ID}}

      - name: Check Docker Image
        run: |
          docker run -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
                     -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY \
                     -e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
                     -e RF_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
                     manishsingh10895/redflag:latest --from $GITHUB_SHA --to $GITHUB_SHA --repo $GITHUB_REPOSITORY \
                     --bedrock-model-id anthropic.claude-3-sonnet-20240229-v1:0 \
                     --bedrock-profile default 
                     --bedrock-region us-east-1